// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.2
// source: transactions/transactions.proto

package transactions

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TransactionsPipelineClient is the client API for TransactionsPipeline service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransactionsPipelineClient interface {
	CommitTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*Status, error)
}

type transactionsPipelineClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionsPipelineClient(cc grpc.ClientConnInterface) TransactionsPipelineClient {
	return &transactionsPipelineClient{cc}
}

func (c *transactionsPipelineClient) CommitTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/transactionsPipeline.transactionsPipeline/CommitTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionsPipelineServer is the server API for TransactionsPipeline service.
// All implementations must embed UnimplementedTransactionsPipelineServer
// for forward compatibility
type TransactionsPipelineServer interface {
	CommitTransaction(context.Context, *Transaction) (*Status, error)
	mustEmbedUnimplementedTransactionsPipelineServer()
}

// UnimplementedTransactionsPipelineServer must be embedded to have forward compatible implementations.
type UnimplementedTransactionsPipelineServer struct {
}

func (UnimplementedTransactionsPipelineServer) CommitTransaction(context.Context, *Transaction) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitTransaction not implemented")
}
func (UnimplementedTransactionsPipelineServer) mustEmbedUnimplementedTransactionsPipelineServer() {}

// UnsafeTransactionsPipelineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionsPipelineServer will
// result in compilation errors.
type UnsafeTransactionsPipelineServer interface {
	mustEmbedUnimplementedTransactionsPipelineServer()
}

func RegisterTransactionsPipelineServer(s grpc.ServiceRegistrar, srv TransactionsPipelineServer) {
	s.RegisterService(&TransactionsPipeline_ServiceDesc, srv)
}

func _TransactionsPipeline_CommitTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionsPipelineServer).CommitTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transactionsPipeline.transactionsPipeline/CommitTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionsPipelineServer).CommitTransaction(ctx, req.(*Transaction))
	}
	return interceptor(ctx, in, info, handler)
}

// TransactionsPipeline_ServiceDesc is the grpc.ServiceDesc for TransactionsPipeline service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransactionsPipeline_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transactionsPipeline.transactionsPipeline",
	HandlerType: (*TransactionsPipelineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CommitTransaction",
			Handler:    _TransactionsPipeline_CommitTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transactions/transactions.proto",
}
